// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iruqnleqjudknkxqdvbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlydXFubGVxanVka25reHFkdmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTcwNzgsImV4cCI6MjA2MDQ3MzA3OH0.dSTJfdfC8E1XvhWJ-7xSlSbM6pYNxjObPCvNY86rSGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);